# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      disable_mustache: true
      disable_phpdoc: true
      disable_phplint: true
      disable_phpcpd: true
      disable_phpcs: true
      disable_grunt: true
